export const SECTIONS = [
  {
    id: 1,
    path: 'seccion-1',
    name: 'Sección 1',
    description: 'Descubre nuestra primera sección con contenido interactivo y animaciones fluidas que cautivan.',
    color: '#FF416C',
    gradient: 'linear-gradient(135deg, #FF4B2B 0%, #FF416C 100%)',
  },
  {
    id: 2,
    path: 'seccion-2',
    name: 'Sección 2',
    description: 'Explora soluciones dinámicas, diseñadas para destacar y brindar la mejor experiencia de usuario.',
    color: '#8A2387',
    gradient: 'linear-gradient(135deg, #E94057 0%, #8A2387 100%)',
  },
  {
    id: 3,
    path: 'seccion-3',
    name: 'Sección 3',
    description: 'Conoce los detalles de nuestra arquitectura tecnológica, impulsada por innovación.',
    color: '#00B4DB',
    gradient: 'linear-gradient(135deg, #0083B0 0%, #00B4DB 100%)',
  },
  {
    id: 4,
    path: 'seccion-4',
    name: 'Sección 4',
    description: 'Integración perfecta y rendimiento inigualable para proyectos de alto nivel.',
    color: '#b20a2c',
    gradient: 'linear-gradient(135deg, #fffbd5 0%, #b20a2c 100%)',
  },
  {
    id: 5,
    path: 'seccion-5',
    name: 'Sección 5',
    description: 'Diseño enfocado en accesibilidad y funcionalidad visualmente deslumbrante.',
    color: '#1D976C',
    gradient: 'linear-gradient(135deg, #93F9B9 0%, #1D976C 100%)',
  },
  {
    id: 6,
    path: 'seccion-6',
    name: 'Sección 6',
    description: 'Datos transformados en experiencias significativas a través del diseño de interfaz.',
    color: '#F09819',
    gradient: 'linear-gradient(135deg, #EDDE5D 0%, #F09819 100%)',
  },
  {
    id: 7,
    path: 'seccion-7',
    name: 'Sección 7',
    description: 'El toque final que completa un producto premium e inolvidable.',
    color: '#7b4397',
    gradient: 'linear-gradient(135deg, #dc2430 0%, #7b4397 100%)',
  },
];
